services:
  front-end:
    container_name: front-end
    build: ./front-end
    networks:
      - cc-net
    ports:
      - 5173:5173
    depends_on:
      - api

  api:
    container_name: api
    build: ./api
    networks:
      - cc-net
    ports:
      - 8080:8080
    

networks:
  cc-net: