package dev.janssenbatista.currencyconverter.enums;

import dev.janssenbatista.currencyconverter.models.Currency;

public enum CurrencyEnum {
    USD("Dólar Americano", "USD"),
    AED("Dirham dos Emirados Árabes Unidos", "AED"),
    AFN("Afegani Afegão", "AFN"),
    ALL("Lek Albanês", "ALL"),
    AMD("Dram Armênio", "AMD"),
    ANG("Florim das Antilhas Holandesas", "ANG"),
    AOA("Kwanza Angolano", "AOA"),
    ARS("Peso Argentino", "ARS"),
    AUD("Dólar Australiano", "AUD"),
    AWG("Florim de Aruba", "AWG"),
    AZN("Manat Azerbaijano", "AZN"),
    BAM("Marco Convertível da Bósnia-Herzegovina", "BAM"),
    BBD("Dólar de Barbados", "BBD"),
    BDT("Taka Bangladeshi", "BDT"),
    BGN("Lev Búlgaro", "BGN"),
    BHD("Dinar do Bahrein", "BHD"),
    BIF("Franco do Burundi", "BIF"),
    BMD("Dólar Bermudiano", "BMD"),
    BND("Dólar de Brunei", "BND"),
    BOB("Boliviano Boliviano", "BOB"),
    BRL("Real Brasileiro", "BRL"),
    BSD("Dólar das Bahamas", "BSD"),
    BTN("Ngultrum Butanês", "BTN"),
    BWP("Pula Botswanense", "BWP"),
    BYN("Rublo Bielorrusso", "BYN"),
    BZD("Dólar do Belize", "BZD"),
    CAD("Dólar Canadense", "CAD"),
    CDF("Franco Congolês", "CDF"),
    CHF("Franco Suíço", "CHF"),
    CLP("Peso Chileno", "CLP"),
    CNY("Yuan Chinês", "CNY"),
    COP("Peso Colombiano", "COP"),
    CRC("Colon Costa Riquenho", "CRC"),
    CUP("Peso Cubano", "CUP"),
    CVE("Escudo Cabo-Verdiano", "CVE"),
    CZK("Coroa Tcheca", "CZK"),
    DJF("Franco Djiboutiano", "DJF"),
    DKK("Coroa Dinamarquesa", "DKK"),
    DOP("Peso Dominicano", "DOP"),
    DZD("Dinar Argelino", "DZD"),
    EGP("Libra Egípcia", "EGP"),
    ERN("Nakfa Eritreia", "ERN"),
    ETB("Birr Etíope", "ETB"),
    EUR("Euro", "EUR"),
    FJD("Dólar de Fiji", "FJD"),
    FKP("Libra das Ilhas Falkland", "FKP"),
    FOK("Coroa das Ilhas Faroé", "FOK"),
    GBP("Libra Esterlina", "GBP"),
    GEL("Lari Georgiano", "GEL"),
    GGP("Libra de Guernsey", "GGP"),
    GHS("Cedi Ganês", "GHS"),
    GIP("Libra de Gibraltar", "GIP"),
    GMD("Dalasi Gambiano", "GMD"),
    GNF("Franco da Guiné", "GNF"),
    GTQ("Quetzal Guatemalteco", "GTQ"),
    GYD("Dólar Guianense", "GYD"),
    HKD("Dólar de Hong Kong", "HKD"),
    HNL("Lempira Hondurenha", "HNL"),
    HRK("Kuna Croata", "HRK"),
    HTG("Gourde Haitiano", "HTG"),
    HUF("Forint Húngaro", "HUF"),
    IDR("Rupia Indonésia", "IDR"),
    ILS("Novo Shekel Israelense", "ILS"),
    IMP("Libra da Ilha de Man", "IMP"),
    INR("Rupia Indiana", "INR"),
    IQD("Dinar Iraquiano", "IQD"),
    IRR("Rial Iraniano", "IRR"),
    ISK("Coroa Islandesa", "ISK"),
    JEP("Libra de Jersey", "JEP"),
    JMD("Dólar Jamaicano", "JMD"),
    JOD("Dinar Jordaniano", "JOD"),
    JPY("Iene Japonês", "JPY"),
    KES("Xelim Queniano", "KES"),
    KGS("Som Quirguiz", "KGS"),
    KHR("Riel Cambojano", "KHR"),
    KID("Dólar de Kiribati", "KID"),
    KMF("Franco das Comores", "KMF"),
    KRW("Won Sul-Coreano", "KRW"),
    KWD("Dinar Kuwaitiano", "KWD"),
    KYD("Dólar das Ilhas Cayman", "KYD"),
    KZT("Tenge Cazaque", "KZT"),
    LAK("Kip Laosiano", "LAK"),
    LBP("Libra Libanesa", "LBP"),
    LKR("Rupia do Sri Lanka", "LKR"),
    LRD("Dólar Liberiano", "LRD"),
    LSL("Loti do Lesoto", "LSL"),
    LYD("Dinar Líbio", "LYD"),
    MAD("Dirham Marroquino", "MAD"),
    MDL("Leu Moldavo", "MDL"),
    MGA("Ariary Malgaxe", "MGA"),
    MKD("Dinar Macedônio", "MKD"),
    MMK("Kyat Mianmarense", "MMK"),
    MNT("Tugrik Mongol", "MNT"),
    MOP("Pataca Macaense", "MOP"),
    MRU("Ouguiya Mauritana", "MRU"),
    MUR("Rupia Mauriciana", "MUR"),
    MVR("Rupia Maldivana", "MVR"),
    MWK("Kwacha Malauiano", "MWK"),
    MXN("Peso Mexicano", "MXN"),
    MYR("Ringgit Malaio", "MYR"),
    MZN("Metical Moçambicano", "MZN"),
    NAD("Dólar da Namíbia", "NAD"),
    NGN("Naira Nigeriano", "NGN"),
    NIO("Córdoba Nicaraguense", "NIO"),
    NOK("Coroa Norueguesa", "NOK"),
    NPR("Rupia Nepalesa", "NPR"),
    NZD("Dólar da Nova Zelândia", "NZD"),
    OMR("Rial Omani", "OMR"),
    PAB("Balboa Panamenho", "PAB"),
    PEN("Sol Peruano", "PEN"),
    PGK("Kina Papua-Nova Guineense", "PGK"),
    PHP("Peso Filipino", "PHP"),
    PKR("Rupia Paquistanesa", "PKR"),
    PLN("Zloty Polonês", "PLN"),
    PYG("Guarani Paraguaio", "PYG"),
    QAR("Rial Catariano", "QAR"),
    RON("Leu Romeno", "RON"),
    RSD("Dinar Sérvio", "RSD"),
    RUB("Rublo Russo", "RUB"),
    RWF("Franco Ruandês", "RWF"),
    SAR("Riyal Saudita", "SAR"),
    SBD("Dólar das Ilhas Salomão", "SBD"),
    SCR("Rupia das Seychelles", "SCR"),
    SDG("Libra Sudanesa", "SDG"),
    SEK("Coroa Sueca", "SEK"),
    SGD("Dólar de Singapura", "SGD"),
    SHP("Libra de Santa Helena", "SHP"),
    SLE("Leone Serra Leoa", "SLE"),
    SLL("Leone Serra Leoa", "SLL"),
    SOS("Xelim Somali", "SOS"),
    SRD("Dólar Surinamês", "SRD"),
    SSP("Libra Sul-Sudanesa", "SSP"),
    STN("Dobra de São Tomé e Príncipe", "STN"),
    SYP("Libra Síria", "SYP"),
    SZL("Lilangeni Suazilandês", "SZL"),
    THB("Baht Tailandês", "THB"),
    TJS("Somoni Tadjique", "TJS"),
    TMT("Manat Turcomeno", "TMT"),
    TND("Dinar Tunisiano", "TND"),
    TOP("Pa'anga Tonganês", "TOP"),
    TRY("Lira Turca", "TRY"),
    TTD("Dólar de Trinidad e Tobago", "TTD"),
    TVD("Dólar de Tuvalu", "TVD"),
    TWD("Novo Dólar Taiwanês", "TWD"),
    TZS("Xelim Tanzaniano", "TZS"),
    UAH("Hryvnia Ucraniano", "UAH"),
    UGX("Xelim Ugandense", "UGX"),
    UYU("Peso Uruguaio", "UYU"),
    UZS("Som Uzbeque", "UZS"),
    VES("Bolívar Venezuelano", "VES"),
    VND("Dong Vietnamita", "VND"),
    VUV("Vatu de Vanuatu", "VUV"),
    WST("Tala Samoano", "WST"),
    XAF("Franco CFA de África Central", "XAF"),
    XCD("Dólar do Caribe Oriental", "XCD"),
    XDR("Direitos Especiais de Saque", "XDR"),
    XOF("Franco CFA de África Ocidental", "XOF"),
    XPF("Franco CFP", "XPF"),
    YER("Rial Iemenita", "YER"),
    ZAR("Rand Sul-Africano", "ZAR"),
    ZMW("Kwacha Zambiano", "ZMW"),
    ZWL("Dólar do Zimbábue", "ZWL");

    private final String currencyName;
    private final String currency;

    CurrencyEnum(String currencyName, String currency) {
        this.currencyName = currencyName;
        this.currency = currency;
    }

    public Currency toEntity() {
        return new Currency(currency, currencyName);
    }
}
